travis:
  secure:
    BINSTAR_TOKEN: sRl6wr5wi/KPACNoPR1eUsRznUIISt95DMBeVNSLlCO0Q5V7nPb5k+oOlBMsgxq2JO1WghZlPMhtrQdMq6gpJ8WusKJq3KxDn3zO0en7m3pD9eXcEcVAbeo/QDHibUEao/DOzqAPHnM3taJjBc4hcOeM7Z9rB1bM6rsjmpcr1pd9hwIjIuWNyk9GIeMp0iqDI7WyKnNhfuIm9V3p2hv9DUkb2+EGLXMPGa1vy4MZLAOumIzgjQ9MbS4sUO+Fq7kEeY8/LDMjRusjItrxfpRetAzPuO2Js2ANSs5vSiVCyAMvoqa1XjCyhG7ccSsZPK8/AA/vOnVEQadexQkLfHmNskG9R54zimie+6rOqYwI8B+PzayloKQbpcmuGbcS3gj9xBiAe3q9HulGcXFrOpfAQnvNdsi7YubUkwQrnZpqzWbyVcEdEAZeW6oC7GAEfpQrXZVCU/KJRJNed102yvMN5v297PG9q9iyBR/B+3HnDrwUtsJX89PmkrgONMAAfsqy0RhfzZTNmOekx72iycmOy6OgoObBK0+JzqAktxA+AICn8W9r+J9DnCwHpM8e/5E9kDS+WBetdd4GL2vc4wIr4Zrs7W//cp0kKDjgY0qYKILtCpqMrp18/Pug3vU/dhaoFCnnfmgoKAldBsY/b4zX/8Fvr8gwfp818rRJuqhV9HE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
